module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "anchovy-anchovy-0": "var(--anchovy-anchovy-0)",
        "anchovy-anchovy-100": "var(--anchovy-anchovy-100)",
        "anchovy-anchovy-20": "var(--anchovy-anchovy-20)",
        "anchovy-anchovy-40": "var(--anchovy-anchovy-40)",
        "anchovy-anchovy-70": "var(--anchovy-anchovy-70)",
        "apple-apple-100": "var(--apple-apple-100)",
        baseprimarypurple: "var(--baseprimarypurple)",
        baseprimarypurplelight: "var(--baseprimarypurplelight)",
        basesecondarygreen: "var(--basesecondarygreen)",
        basesecondaryred: "var(--basesecondaryred)",
        basesecondaryyellow: "var(--basesecondaryyellow)",
        borderalpha: "var(--borderalpha)",
        "borderalpha-light": "var(--borderalpha-light)",
        "borderborder-1": "var(--borderborder-1)",
        "borderborder-2": "var(--borderborder-2)",
        "borderborder-3": "var(--borderborder-3)",
        "borderborder-4": "var(--borderborder-4)",
        borderlight: "var(--borderlight)",
        "chili-jam-chili-jam-100": "var(--chili-jam-chili-jam-100)",
        fillalpha: "var(--fillalpha)",
        "fillalpha-light": "var(--fillalpha-light)",
        "fillfill-1": "var(--fillfill-1)",
        "fillfill-2": "var(--fillfill-2)",
        "fillfill-3": "var(--fillfill-3)",
        "fillfill-4": "var(--fillfill-4)",
        "fillfill-5": "var(--fillfill-5)",
        "fillfill-6": "var(--fillfill-6)",
        "foundation-orangeorange-500": "var(--foundation-orangeorange-500)",
        "foundation-orangeorange-700": "var(--foundation-orangeorange-700)",
        "foundation-orangeorange-900": "var(--foundation-orangeorange-900)",
        "foundationpeople-heart200": "var(--foundationpeople-heart200)",
        "foundationpeople-heart300": "var(--foundationpeople-heart300)",
        "foundationpeople-heart900": "var(--foundationpeople-heart900)",
        "foundationpeople-heart950": "var(--foundationpeople-heart950)",
        "kelp-kelp-100": "var(--kelp-kelp-100)",
        "kelp-kelp-40": "var(--kelp-kelp-40)",
        "kelp-kelp-70": "var(--kelp-kelp-70)",
        "lightbgbg-secondary": "var(--lightbgbg-secondary)",
        lighttextdefaultdefault: "var(--lighttextdefaultdefault)",
        "mulberry-mulberry-80": "var(--mulberry-mulberry-80)",
        "mustard-mustard-20": "var(--mustard-mustard-20)",
        "mustard-mustard-30": "var(--mustard-mustard-30)",
        "mustard-mustard-70": "var(--mustard-mustard-70)",
        "pumpkin-pumpkin-100": "var(--pumpkin-pumpkin-100)",
        "purple-heart300": "var(--purple-heart300)",
        "surfacebackground-0": "var(--surfacebackground-0)",
        "surfacebackground-1": "var(--surfacebackground-1)",
        "surfacebackground-2": "var(--surfacebackground-2)",
        "surfacebackground-3": "var(--surfacebackground-3)",
        surfaceinverse: "var(--surfaceinverse)",
        textinverse: "var(--textinverse)",
        textprimary: "var(--textprimary)",
        "textwhite-100": "var(--textwhite-100)",
        "textwhite-20": "var(--textwhite-20)",
        "textwhite-30": "var(--textwhite-30)",
        "textwhite-50": "var(--textwhite-50)",
        "textwhite-70": "var(--textwhite-70)",
        "textwhite-85": "var(--textwhite-85)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-12": "var(--body-12-font-family)",
        "body-13": "var(--body-13-font-family)",
        "body-14": "var(--body-14-font-family)",
        "body-15": "var(--body-15-font-family)",
        "body-16": "var(--body-16-font-family)",
        "body-20": "var(--body-20-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-medium": "var(--body-medium-font-family)",
        "display-m": "var(--display-m-font-family)",
        "display-s": "var(--display-s-font-family)",
        "heading-small": "var(--heading-small-font-family)",
        "heading-x-small": "var(--heading-x-small-font-family)",
        "headline-s": "var(--headline-s-font-family)",
        "headline-XL": "var(--headline-XL-font-family)",
        "label-11": "var(--label-11-font-family)",
        "label-12": "var(--label-12-font-family)",
        "label-14": "var(--label-14-font-family)",
        "label-14-emphasized": "var(--label-14-emphasized-font-family)",
        "label-14-medium": "var(--label-14-medium-font-family)",
        "label-16-emphasized": "var(--label-16-emphasized-font-family)",
        "label-16-medium": "var(--label-16-medium-font-family)",
        "label-l": "var(--label-l-font-family)",
        "label-l-emphasized": "var(--label-l-emphasized-font-family)",
        "label-m": "var(--label-m-font-family)",
        "label-m-emphasized": "var(--label-m-emphasized-font-family)",
        "label-s": "var(--label-s-font-family)",
        "label-XL": "var(--label-XL-font-family)",
        "label-XL-emphasized": "var(--label-XL-emphasized-font-family)",
        "title-15-emphasized": "var(--title-15-emphasized-font-family)",
        "title-16-emphasized": "var(--title-16-emphasized-font-family)",
        "title-18-emphasized": "var(--title-18-emphasized-font-family)",
        "title-20-emphasized": "var(--title-20-emphasized-font-family)",
        "title-24-emphasized": "var(--title-24-emphasized-font-family)",
        "title-32-emphasized": "var(--title-32-emphasized-font-family)",
        "title-36-emphasized": "var(--title-36-emphasized-font-family)",
        "title-72-emphasized": "var(--title-72-emphasized-font-family)",
        "title-l": "var(--title-l-font-family)",
        "title-l-emphasized": "var(--title-l-emphasized-font-family)",
        "title-XL": "var(--title-XL-font-family)",
        "title-XL-emphasized": "var(--title-XL-emphasized-font-family)",
        "title-XS": "var(--title-XS-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        chatbot: "var(--chatbot)",
        modal: "var(--modal)",
        "shadow-down-medium": "var(--shadow-down-medium)",
        "shadow-xs": "var(--shadow-xs)",
        "shallow-shadow": "var(--shallow-shadow)",
        "tips-shadow": "var(--tips-shadow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
